package:
  name: lapack
  version: 3.5.0

source:
  fn: lapack-3.5.0.tgz
  url: http://www.netlib.org/lapack/lapack-3.5.0.tgz

requirements:
    build:
        - cmake
        - python
    run:
        - libgfortran
about:
    home: http://www.netlib.org/lapack
    license: GNU Lesser General Public License (LGPL)

