package:
  name: parmed-dev
  version: 2.0.2

source:
  git_url: https://github.com/parmed/parmed
  git_tag: master

requirements:
  build:
    - numpy
  run:
    - numpy

about:
    home: http://parmed.github.io/ParmEd 
    license: LESSER GPL
    summary: Cross-program parameter and topology file editor and molecular mechanical simulator engine. 
