package:
  name: parmed
  version: !!str 2.3.2

source:
  git_url: https://github.com/ParmEd/ParmEd.git
  git_tag: master

requirements:
  build:
    - python
    - numpy
    - setuptools

  run:
    - python
    - numpy

test:
  commands:
    - python -c 'import parmed as pmd; print(pmd.load_file)'


about:
  home: http://parmed.github.io/ParmEd
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: A package for parsing, interconverting, manipulating, and simulating biomolecular simulations with many packages
