package:
  name: nglview
  version: !!str 0.4dev

source:
  git_url: https://github.com/hainm/nglview
  git_tag: master

requirements:
  build:
    - python
    - setuptools
    - ipython
    - ipywidgets
    - traitlets
  run:
    - python
    - pytraj-dev
    - ipywidgets
    - ipython
    - traitlets

test:
  commands:
    - python -c 'import nglview as nv; nv.Structure("")'

about:
  home: https://github.com/arose/nglview 
  license: MIT
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
