package:
  name: nglview-dev
  version: !!str 0.5.dev

source:
  git_url: https://github.com/arose/nglview
  git_tag: master

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - ipywidgets
    - traitlets
  run:
    - python
    - ipywidgets
    - jupyter
    - traitlets
    - notebook

test:
  commands:
    - python -c 'import nglview as nv'

about:
  home: https://github.com/arose/nglview 
  license: MIT
  summary: An IPython widget to interactively view molecular structures and trajectories. Utilizes the embeddable NGL Viewer for rendering.
