package:
  name: libcpptraj-dev
  version: 4.2.7

source:
  git_url: https://github.com/amber-md/cpptraj.git
  git_tag: master

requirements:
  build:
    - zlib
    - bzip2
    - libnetcdf
    - lapack
  run:
    - zlib
    - bzip2
    - libnetcdf
    - libgfortran
    - lapack

about:
    home: https://github.com/amber-md/cpptraj/
    license: GNU
    summary: Biomolecular simulation trajectory/data analysis. 
