package:
  name: libcpptraj-dev
  version: 4.2.7

source:
  git_url: https://github.com/amber-md/cpptraj.git
  git_tag: master

requirements:
  build:
    - zlib
    - bzip2
    - libnetcdf
    - lapack
    - arpack
    - blas
    - libgfortran
  run:
    - zlib
    - bzip2
    - libnetcdf
    - lapack
    - arpack
    - blas
    - libgfortran

about:
    home: https://github.com/amber-md/cpptraj/
    license: GNU
    summary: libcpptraj
