package:
  name: libcpptraj
  version: 4.3.1

source:
  git_url: https://github.com/amber-md/cpptraj.git
  git_tag: master

requirements:
  build:
    - zlib
    - bzip2
    - libnetcdf
    - openblas [linux]
  run:
    - zlib
    - bzip2
    - libnetcdf
    - openblas [linux]
    - libgfortran [linux]

about:
    home: https://github.com/amber-md/cpptraj/
    license: GPL v3
    summary: Biomolecular simulation trajectory/data analysis. 
