
package:
  name: pytraj
  version: !!str 1.0.3

source:

  fn: pytraj-1.0.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pytraj/pytraj-1.0.3.tar.gz


requirements:
  build:
    - python
    - cython
    - libcpptraj 4.3.0
    - libnetcdf
  run:
    - python
    - libcpptraj 4.3.0
    - libnetcdf
    - numpy

test:
  commands:
    - python -c 'import pytraj as pt; pt.show_versions(); from pytraj.testing import get_remd_fn'

about:
  home: http://github.com/amber-md/pytraj
  license: GPL v3
  summary: Python API for cpptraj - a package for data analysis of MD simulations
