
package:
  name: pytraj-dev
  version: !!str 1.0.3.dev

source:

  git_url: https://github.com/amber-md/pytraj.git
  git_tag: master


requirements:
  build:
    - python
    - cython
    - libcpptraj 4.3.0
    - libnetcdf
  run:
    - python
    - libcpptraj 4.3.0
    - libnetcdf
    - numpy

test:
  commands:
    - python -c 'import pytraj as pt; pt.show_versions(); from pytraj.testing import get_remd_fn'

about:
  home: http://github.com/amber-md/pytraj
  license: BSD
  summary: Python API for cpptraj - a package for data analysis of MD simulations
